[build-system]
requires = ["poetry-core>=1.0.8"]
build-backend = "poetry.core.masonry.api"

[tool]
  [tool.commitizen]
  version = "0.2.0"
  version_files = [
    ".pre-commit-config.yaml:rev.\\s+(?=[^\\n]+Commitizen)",
    "pyproject.toml:version"
  ]

  [tool.poetry]
  name = "pre-commit-hooks"
  version = "0.2.0"
  description = "Hooks for Use With the pre-commit Framework"
  authors = ["Kurt von Laven <kurt.von.laven@gmail.com>"]
  license = "MIT"

  [tool.poetry.dependencies]
  python = "^3.10.4"

  [tool.poetry.dev-dependencies]
  commitizen = "^2.23.0"
  pre-commit = "^2.18.1"
